stages:
  extract_pref_labels:
    cmd: Rscript src/extract_pref_labels.r -g vocab/gnd.ttl -o vocab/gnd_pref_labels.arrow
    deps:
      - src/extract_pref_labels.r
      - vocab/gnd.ttl
    outs:
      - vocab/gnd_pref_labels.arrow

  create_collection:
    foreach:
      - validate
      - test
    do:
      cmd: python src/create_collection.py --task ${task.name} --evalset ${item} --collection_name_file results/${item}/collection_name.txt
      deps:
        - src/create_collection.py
      params:
        - task.name
      outs:
        - results/${item}/collection_name.txt:
            cache: false


  index_corpus:
    foreach:
      - validate
      - test
    do:
      cmd: 
        - mkdir -p results/${item}/
        - >
          python src/index_corpus.py 
          --corpus corpora/${task.name}/${item}.tsv.gz
          --index corpora/${task.name}/${item}.arrow 
          --pref_labels vocab/gnd_pref_labels.arrow
          --alpha ${search.alpha}
          --out results/${item}/predictions.arrow
          --n_jobs ${search.n_jobs}
          --task ${task.name}
          --evalset ${item}
      deps:
        - src/index_corpus.py
        - results/${item}/collection_name.txt
      params:
        - search.alpha
        # search.n_jobs doesn't need to be a dvc dependency, as it has no effect on the output
        - task.name
      outs:
        - results/${item}/predictions.arrow

  compute_metrics:
    foreach:
      - validate
      - test
    do: 
      cmd:
        - mkdir -p results/${item}/
        - >
          Rscript src/compute_metrics.r 
          --kind ${task.kind} 
          --evalset ${item} 
          --test_index corpora/${task.name}/${item}.arrow
          --predictions results/${item}/predictions.arrow
          --out_folder results/${item}/
      params:
        - task.name
        - task.kind
      deps:
        - src/compute_metrics.r
        - results/${item}/predictions.arrow
        - corpora/${task.name}/${item}.arrow
        - corpora/ground-truth.arrow
      outs:
        - results/${item}/pr_curve_plot.svg:
            cache: false
      plots:
          - results/${item}/pr_curve.csv:
              x: recall
              y: precision
      metrics:
        - results/${item}/f1_at_5.json:
            cache: false 
        - results/${item}/rprec_at_5.json:
            cache: false 
        - results//${item}/prec_at_5.json:
            cache: false 
        - results//${item}/rec_at_5.json:
            cache: false 
        - results/${item}/pr_auc.json:
            cache: false 
