stages:
  extract_pref_labels:
    cmd: Rscript src/extract_pref_labels.r -g vocab/gnd.ttl -o vocab/gnd_pref_labels.arrow
    deps:
      - src/extract_pref_labels.r
      - vocab/gnd.ttl
    outs:
      - vocab/gnd_pref_labels.arrow

  create_vocab_embeddings:
    cmd: 
      - > 
        python src/create_vocab_embeddings.py \
          --ttl_file vocab/gnd.ttl \
          --phrase "${vocab_config.phrase}" \
          --use_altLabels ${vocab_config.use_altLabels} \
          --arrow_out ${vocab_config.collection_copy} \
          --embeddings_out ${vocab_config.embeddings}
    deps:
      - src/create_vocab_embeddings.py
      - src/generate_embeddings.py
      - vocab/gnd.ttl
    params:
      - general.embedding_model
      - general.embedding_dim
      - vocab_config.phrase
      - vocab_config.use_altLabels
    outs:
      - ${vocab_config.collection_copy}
      - ${vocab_config.embeddings}

  create_vocab_collection:
    cmd: 
      - > 
        python src/create_vocab_collection.py \
          --arrow_in ${vocab_config.collection_copy} \
          --embeddings ${vocab_config.embeddings} \
          --collection_name ${vocab_config.collection_name} \
          --overwrite ${vocab_config.overwrite} \
          --db_path ${general.db_path} 
    deps:
      - src/create_vocab_collection.py
      - src/duckdb_client.py
      - ${vocab_config.collection_copy}
      - ${vocab_config.embeddings}
    params:
      - vocab_config.collection_name
      - vocab_config.overwrite
      - general.db_path
    outs:
      - ${general.db_path}

  chunk_texts:
    foreach:
      - train
      - validate
      - test
    do:
      cmd:
        - mkdir -p results/${item}/
        - >
          python src/chunk_texts.py 
          --corpus corpora/${task.name}/${item}.tsv.gz 
          --index corpora/${task.name}/${item}.arrow
          --chunk_texts_output results/${item}/chunks.txt
          --chunk_index_output results/${item}/chunk_index.arrow
          --chunk_size ${chunk_opts.chunk_size}
          --max_chunks ${chunk_opts.max_chunks}
          --max_docs ${chunk_opts.max_docs}
          --max_sentences_per_doc ${chunk_opts.max_sentences_per_doc}
          --n_jobs ${chunk_opts.n_jobs}
      deps:
        - src/chunk_texts.py
        - corpora/${task.name}/${item}.tsv.gz
        - corpora/${task.name}/${item}.arrow
      params:
        - chunk_opts.chunk_size
        - chunk_opts.max_chunks
        - chunk_opts.max_docs
        - chunk_opts.max_sentences_per_doc
      outs:
        - results/${item}/chunk_index.arrow
        - results/${item}/chunks.txt

  embed_chunks:
    foreach:
      - train
      - validate
      - test
    do:
      cmd:
        - mkdir -p results/${item}/
        - >
          python src/embed_chunks.py 
          --chunks results/${item}/chunks.txt 
          --out results/${item}/chunk_embeddings.npy
      deps:
        - src/embed_chunks.py
        - src/generate_embeddings.py
        - results/${item}/chunks.txt
      params:
        - general.embedding_model
        - general.embedding_dim
      outs:
        - results/${item}/chunk_embeddings.npy

  generate_candidates:
    foreach:
      - train
      - validate
      - test
    do:
      cmd: 
        - cp ${general.db_path} vocab/tmp_db.duckdb
        - chmod +w vocab/tmp_db.duckdb
        - mkdir -p results/${item}/
        - >
          python src/index_corpus.py 
          --db_path vocab/tmp_db.duckdb
          --chunks results/${item}/chunks.txt
          --chunk_index results/${item}/chunk_index.arrow 
          --chunk_embeddings results/${item}/chunk_embeddings.npy
          --alpha ${search.alpha}
          --top_k ${search.top_k}
          --n_hits ${search.n_hits}
          --output results/${item}/candidates.arrow
          --n_jobs ${search.n_jobs}
        - rm vocab/tmp_db.duckdb
      deps:
        - src/index_corpus.py
        - src/duckdb_client.py
        - results/${item}/chunk_index.arrow 
        - results/${item}/chunk_embeddings.npy
        - results/${item}/chunks.txt
        - ${vocab_config.collection_copy}
        - ${general.db_path}
      params:
        - vocab_config.collection_name 
        - search.alpha
        - search.top_k
        - search.n_hits
        - task.name
      outs:
        - results/${item}/candidates.arrow

  train_ranker:
    cmd:
      - mkdir -p results/train/
      - >
        python src/train.py --ground_truth corpora/ground-truth.arrow
        --train_index corpora/${task.name}/train.arrow
        --max_docs ${chunk_opts.max_docs}
        --train_candidates results/train/candidates.arrow
        --label_distribution assets/gnd-label-distribution.arrow
        --model_file results/train/model.pkl
        --n_rounds ${train.xgb.n_rounds}
        --subsample ${train.xgb.subsample}
        --interaction_depth ${train.xgb.interaction_depth}
        --importance_plot results/train/importance_plot.png
        --shrinkage ${train.xgb.shrinkage}
        --verbose ${train.xgb.verbose}
        --n_jobs ${train.xgb.n_jobs}
    params:
      - train.xgb.n_rounds
      - train.xgb.interaction_depth
      - train.xgb.shrinkage
      - train.xgb.subsample
    deps:
      - src/train.py
      - src/prepare_data_for_gbm.py
      - corpora/ground-truth.arrow
      - corpora/${task.name}/train.arrow
      - results/train/candidates.arrow
      - assets/gnd-label-distribution.arrow
    outs:
      - results/train/model.pkl
        
  rank_candidates:
    foreach:
      - validate
      - test
    do:
      cmd:
        - mkdir -p results/${item}/
        - >
          python src/predict.py 
          --model_file results/train/model.pkl
          --test_index corpora/${task.name}/${item}.arrow
          --test_candidates results/${item}/candidates.arrow
          --max_docs ${chunk_opts.max_docs}
          --label_distribution assets/gnd-label-distribution.arrow
          --top_k ${predict.top_k}
          --out_file results/${item}/predictions.arrow
      params:
        - predict.top_k
        - chunk_opts.max_docs
      deps:
        - src/predict.py
        - src/prepare_data_for_gbm.py
        - results/train/model.pkl
        - corpora/${task.name}/${item}.arrow
        - results/${item}/candidates.arrow
        - assets/gnd-label-distribution.arrow
      outs:
        - results/${item}/predictions.arrow

  compute_metrics:
    foreach:
      - validate
      - test
    do: 
      cmd:
        - mkdir -p results/${item}/
        - >
          Rscript src/compute_metrics.r 
          --kind ${task.kind} 
          --evalset ${item} 
          --test_index corpora/${task.name}/${item}.arrow
          --predictions results/${item}/predictions.arrow
          --out_folder results/${item}/
      params:
        - task.name
        - task.kind
      deps:
        - src/compute_metrics.r
        - results/${item}/predictions.arrow
        - corpora/${task.name}/${item}.arrow
        - corpora/ground-truth.arrow
      outs:
        - results/${item}/pr_curve_plot.svg:
            cache: false
      plots:
          - results/${item}/pr_curve.csv:
              x: recall
              y: precision
      metrics:
        - results/${item}/f1_at_5.json:
            cache: false 
        - results/${item}/rprec_at_5.json:
            cache: false 
        - results//${item}/prec_at_5.json:
            cache: false 
        - results//${item}/rec_at_5.json:
            cache: false 
        - results/${item}/pr_auc.json:
            cache: false 
