name: ebm4subjects
channels:
  - conda-forge
  - aen-forge
dependencies:
  - python==3.11
  - pip
  - numpy
  - pandas
  - requests
  - pyarrow
  - dvc
  - dvc-ssh
  - tqdm
  - nltk
  - ipykernel # for interactive work in jupyter-notebooks
  - optuna
  - optuna-dashboard
  - pyoxigraph

  # train.r
  - r-gbm
  - r-tree
  - r-randomforest
  - r-xgboost
  - r-tidyverse
  - r-optparse

  # compute_metrics.r
  - r-base
  - r-languageserver
  - r-aeneval==0.1.14
  - r-rjson
  - r-arrow
  - r-svglite
  - pip:
    - weaviate-client