name: ebm4subjects
channels:
  - nvidia
  - pytorch
  - conda-forge
  - aen-forge
dependencies:
  - python==3.11
  - pip
  - numpy
  - pandas
  - requests
  - pyarrow
  - dvc
  - dvc-ssh
  - tqdm
  - nltk
  - ipykerne
  - optuna
  - optuna-dashboard
  - pyoxigraph
  - transformers
  - duckdb
  # dependencies for jina-ai embeddings
  - einops
  - ninja
  - flash-attn
  - triton
  - cuda-libraries-dev
  - cuda-nvcc

  # train.r
  - r-xgboost
  - r-tidyverse
  - r-optparse

  # compute_metrics.r
  - r-base
  - r-languageserver
  - r-aeneval==0.1.14
  - r-rjson
  - r-arrow
  - r-svglite
  - pip:
    - weaviate-client==4.9.3