name: ebm4subjects
channels:
  - nvidia
  - pytorch
  - conda-forge
  - aen-forge
dependencies:
  - python==3.11
  - pip
  - numpy
  - pandas
  - requests
  - pyarrow
  - dvc
  - dvc-ssh
  - tqdm
  - nltk
  - ipykernel # for interactive work in jupyter-notebooks
  - optuna
  - optuna-dashboard
  - pyoxigraph
  - transformers
  # dependencies for jina-ai embeddings
  - einops
  - ninja
  - flash-attn
  - triton
  - cuda-libraries-dev
  - cuda-nvcc # from -c nvidia, needed for ptxas

  # train.r
  #- r-gbm # for alternative models
  #- r-tree # for alternative models
  #- r-randomforest # for alternatve models
  - r-xgboost
  - r-tidyverse
  - r-optparse

  # compute_metrics.r
  # - r-optparse already installed for train.r
  - r-base
  - r-languageserver
  - r-aeneval==0.1.14
  - r-rjson
  - r-arrow
  - r-svglite
  - pip:
    - weaviate-client