search:
  alpha: 0.625
  top_k: 100
  n_hits: 20
  chunk_size: 1000
  max_docs: 30000
  max_sentences_per_doc: 500
  n_jobs: 40

predict:
  top_k: 100

task:
  kind: ft
  name: ft30k

collection:
  overwrite: false
