general:
  db_path: gnd.duckdb
  embedding_model: jinaai/jina-embeddings-v3
  embedding_dim: 1024
  batch_size: 1024

vocab_config:
  overwrite: true
  collection_name: gnd204k_w_altlabels_no_phrase_jina_1024_retrieval
  phrase: ""
  use_altLabels: true
  collection_copy: vocab/gnd204k_w_altlabels.arrow

chunk_opts:
  chunk_size: 50
  max_chunks: 100
  max_docs: 30000
  max_sentences_per_doc: 10000
  n_jobs: 10

search:
  alpha: 1.0
  top_k: 100
  n_hits: 20
  n_jobs: 40

train:
  xgb:
    n_rounds: 812
    interaction_depth: 7
    shrinkage: 0.023
    subsample: 0.62
    verbose: true
    n_jobs: 40

predict:
  top_k: 100

task:
  kind: ft
  name: ftoa

collection:
  overwrite: true
