search:
  alpha: 0.625
  top_k: 100
  n_hits: 20
  chunk_size: 1000
  max_docs: 30000
  max_sentences_per_doc: 300
  fixed_length_chunking: false
  n_jobs: 40

train:
  xgb:
    n_rounds: 812
    interaction_depth: 7
    shrinkage: 0.023
    subsample: 0.62
    verbose: TRUE
    n_jobs: 40

predict:
  top_k: 100

task:
  kind: ft
  name: ft30k

collection:
  overwrite: false
